### ISSUE TITLE
localhost always added to BookKeeper connection string by Python script

### ISSUE THREAD

**Issue by lucperkins** [streamlio/docker-images#4]
I've been attempting to run BookKeeper on Kubernetes, and a problem that I've been running into thus far is that bookies are failing to start because the connection string that they're supplied with (via `BK_zkServers`) always includes the `localhost:2181` address. And so this means that setting `BK_zkServers` to `zk-0,zk-1,zk-2` yields this in the logs:

```
Hello, I'm your bookie, listening on port 3181. ZKServers are on zookeeper-0,zookeeper-1,zookeeper-2,localhost:2181
```

**Comment by zhaijack** [comment]
Hi @lucperkins , How do you run it? May need more details.

**Comment by zhaijack** [comment]
Hi @lucperkins, Thanks for the report. have fixed by this, https://github.com/streamlio/docker-images/commit/47b199c6394e46886ea106c97c089aeeb83fa85d
would you please help verify it again?

**Comment by lucperkins** [comment]
@zhaijack I ran this locally setting `BK_zkServers` to `zk0,zk1,zk2` and got the expected debug output, so this appears to be fixed 👍
