### ISSUE TITLE
No zkCli.sh script available

### ISSUE THREAD

**Issue by lucperkins** [streamlio/docker-images#5]
I've encountered another issue when running the BookKeeper image (both locally using `docker-machine` and on Kubernetes, using Minikube):

```
/opt/bookkeeper/entrypoint.sh: line 61: /opt/zk/bin/zkCli.sh: No such file or directory
```

It looks like the entrypoint script assumes that ZooKeeper is available on the image. I think that: 

* creating the root node will need to be accomplished some other way, perhaps by running this command on the ZooKeeper nodes themselves
* bookies should start up with the assumption that ZooKeeper is ready to handle them

**Comment by zhaijack** [comment]
Oh. It is replaced by " /opt/bookkeeper/bin/bookkeeper org.apache.zookeeper.ZooKeeperMain",
leak the changing of it. will fix it soon

**Comment by zhaijack** [comment]
Done the fix and tested locally. Thanks a lot for the findings.
